fix helm formating error in geoip sidecar
goauthentik/helm pull request #245
Opened 2024-02-22 18:11 UTC by Schmoaaaaah

2024-02-23 08:30 UTC, rissson requested changes
Thank you for the fix!

2024-02-23 08:30 UTC, rissson commented on charts/authentik/templates/server/deployment.yaml
> +          {{ if .Values.geoip.resources }}
```suggestion
```

2024-02-23 08:30 UTC, rissson commented on charts/authentik/templates/server/deployment.yaml
> +            {{- toYaml .Values.geoip.resources | nindent 10 }}{{ end }}
```suggestion
            {{- toYaml .Values.geoip.resources | nindent 12 }}
```

2024-02-23 08:30 UTC, rissson commented on charts/authentik/templates/worker/deployment.yaml
> +          {{ if .Values.geoip.resources }}
```suggestion
```

2024-02-23 08:30 UTC, rissson commented on charts/authentik/templates/worker/deployment.yaml
> +            {{- toYaml .Values.geoip.resources | nindent 10 }}{{ end }}
```suggestion
            {{- toYaml .Values.geoip.resources | nindent 12 }}
```

2024-02-23 08:31 UTC, rissson approved these changes

2024-02-23 08:33 UTC, merged

2024-02-24 04:46 UTC, stephenwilliams commented
@rissson can we get a version of the chart pushed with this fix